---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgbouncer
  name: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
      - name: azure-pgbouncer-sidecar
        image: mcr.microsoft.com/azure-oss-db-tools/pgbouncer-sidecar:latest
        # Uncomment below if you always want the latest version
        # imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.db_port }}
        volumeMounts:
          - name: configfiles
            mountPath: "/etc/pgbouncer"
            # writes update the secret, we do not want to do this
            readOnly: true
        livenessProbe:
          tcpSocket:
            # This must match the port your applications use to talk to postgres
            port: {{ .Values.db_port }}
          periodSeconds: 60
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['all']
      volumes:
        - name: configfiles
          secret:
              # This must match the name of your secret above
              secretName: azure-pgbouncer-config

---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
spec:
  ports:
    -
      port: {{ .Values.db_port }}
      protocol: TCP
      targetPort: {{ .Values.db_port }}
  selector:
    app: pgbouncer
  type: ClusterIP
